### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by Vstory**
Simplified Chinese translation

### CODE REVIEW

**Comment by dragonofmercy** [comment]
Ok I will do it manually, I close this pull request

**Comment by Vstory** [comment]
Not too aware of the pull, I recreated it.
The web version cannot change the folder name, I have recreated it.

**Comment by dragonofmercy** [comment]
It's ok I submited your changes in the main repository, I will test it and publish it tomorrow it no bugs

**Comment by Vstory** [comment]
> It's ok I submited your changes in the main repository, I will test it and publish it tomorrow it no bugs


Thank you!

**Pull request closed without merging**
